<template>
  <div class="construction-page">
    <section class="dust-hero">
      <div class="container">
        <div class="hero-top">
          <div class="hero-brand">
            <div class="hero-brand-icon">✦</div>
            <span class="hero-brand-name">SAFAIR</span>
            <router-link to="/" class="hero-back-link">‹ Back to Home</router-link>
          </div>
        </div>

        <div class="hero-copy">
          <h1>Construction Dust in Your Area</h1>
          <p>
            Understanding nearby building work and how it might affect your child
          </p>
        </div>
      </div>
    </section>

    <section class="section dust-content">
      <div class="container">
        <div class="suburb-card card">
          <h2>Choose your suburb</h2>
          <p>
            Select your Melbourne suburb to see construction activity and dust risk
            specific to your area
          </p>

          <div class="privacy-controls">
            <label class="privacy-toggle">
              <input
                v-model="locationEnabled"
                type="checkbox"
                @change="saveLocationPreference"
              />
              <span>Enable precise location</span>
            </label>

            <button
              class="suburb-pill"
              :disabled="!locationEnabled || loading"
              @click="useMyLocation"
            >
              {{ loading ? 'Loading...' : 'Use My Location' }}
            </button>
          </div>

          <div class="push-controls">
            <label class="privacy-toggle">
              <input
                v-model="pushEnabled"
                type="checkbox"
                @change="handlePushToggle"
              />
              <span>Enable dust alerts</span>
            </label>

            <button
              class="suburb-pill test-btn"
              :disabled="!pushEnabled || testingPush"
              @click="sendTestPush"
            >
              {{ testingPush ? 'Sending Test...' : 'Send Test Notification' }}
            </button>
          </div>

          <p class="push-help">
            Get notified when dust risk suddenly rises near you
          </p>

          <div class="suburb-grid">
            <button
              v-for="suburb in suburbs"
              :key="suburb"
              class="suburb-pill"
              :class="{ active: suburb === selectedSuburb }"
              @click="selectSuburb(suburb)"
            >
              {{ suburb }}
            </button>
          </div>

          <div class="updated-row">
            <span class="updated-dot">◔</span>
            <span>Last updated: {{ activeArea.lastUpdated }}</span>
          </div>
        </div>

        <div class="risk-summary-card">
          <img
            src="../assets/images/construction-summary-bg.jpg"
            alt="Construction site"
            class="risk-summary-bg"
          />
          <div class="risk-summary-overlay"></div>

          <div class="risk-summary-content">
            <div class="risk-summary-icon">🚧</div>

            <div>
              <p class="risk-summary-tag">
                {{ activeArea.summaryEyebrow }}
              </p>
              <h2>{{ activeArea.summaryTitle }}</h2>
              <p class="risk-summary-text">
                {{ activeArea.summaryText }}
              </p>
              <p v-if="activeArea.riskLevel" class="risk-level-text">
  <div v-if="activeArea.riskLevel" class="risk-highlight">
  <span class="risk-label">Current Risk</span>

  <span
    class="risk-badge"
    :class="activeArea.riskLevel.toLowerCase()"
  >
    {{ activeArea.riskLevel }}
  </span>

  <p class="risk-recommendation">
    {{ activeArea.riskRecommendation }}
  </p>
</div>
  This estimate is generated by our model using wind speed and related environmental data.
</p>

            </div>
          </div>
        </div>

        <ConstructionRiskMap
  v-if="activeArea.activeSites.length"
  :center-lat="mapCenter.lat"
  :center-lon="mapCenter.lon"
  :center-label="mapCenter.label"
  :sites="activeArea.activeSites"
/>

        <div v-if="activeArea.activeSites.length" class="sites-section">
          <h2 class="sites-heading">Active construction sites</h2>

          <div class="sites-list">
            <article
              v-for="site in activeArea.activeSites"
              :key="site.siteId"
              class="site-card"
              :class="site.riskTone"
            >
              <div class="site-card-main">
                <h3>{{ site.title }}</h3>
                <p class="site-card-type">{{ site.type }}</p>
                <p class="site-card-distance">📍 {{ site.distance }}</p>
              </div>

              <div class="site-risk-badge" :class="site.riskTone">
                {{ site.riskLabel }}
              </div>
            </article>
          </div>
        </div>

        <div class="dust-actions-panel">
          <img
            src="../assets/images/actions-bg.jpeg"
            alt="Background"
            class="dust-actions-bg"
          />
          <div class="dust-actions-overlay"></div>

          <div class="dust-actions-content">
            <h2>What you can do today</h2>

            <ul class="dust-actions-list">
              <li v-for="(tip, index) in activeArea.tips" :key="`${tip}-${index}`">
                {{ tip }}
              </li>
            </ul>

            <router-link to="/recommendations" class="dust-actions-btn">
              See Full Action Plan
              <span>→</span>
            </router-link>
          </div>
        </div>

        <p v-if="error" class="error-text">{{ error }}</p>
        <p v-if="successMessage" class="success-text">{{ successMessage }}</p>
      </div>
    </section>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import {
  requestNotificationPermission,
  subscribeToPush,
  unsubscribeFromPush,
} from '../utils/pushNotifications'

import ConstructionRiskMap from '../components/ConstructionRiskMap.vue'

const USER_ID_KEY = 'safair_user_id'
const FALLBACK_SUBURBS = [
  'Carlton',
  'Docklands',
  'East Melbourne',
  'Kensington',
  'Melbourne',
  'North Melbourne',
  'Parkville',
  'South Yarra',
  'Southbank',
  'West Melbourne',
]

const SUBURB_COORDS = {
  Carlton: { lat: -37.8008, lon: 144.9669 },
  Docklands: { lat: -37.8147, lon: 144.9489 },
  'East Melbourne': { lat: -37.8167, lon: 144.9875 },
  Kensington: { lat: -37.7942, lon: 144.9271 },
  Melbourne: { lat: -37.8136, lon: 144.9631 },
  'North Melbourne': { lat: -37.7994, lon: 144.9460 },
  Parkville: { lat: -37.7873, lon: 144.9510 },
  'South Yarra': { lat: -37.8396, lon: 144.9917 },
  Southbank: { lat: -37.8250, lon: 144.9640 },
  'West Melbourne': { lat: -37.8098, lon: 144.9424 },
}

const fallbackArea = {
  lastUpdated: '--:--',
  summaryEyebrow: 'NEARBY CONSTRUCTION SITES',
  summaryTitle: 'No active construction sites nearby',
  summaryText:
    'We could not find active sites near this location right now.',
  riskLevel: null,
  riskRecommendation: '',
  activeSites: [],
  tips: [
    'Carry your reliever inhaler when leaving home',
    'Choose routes away from visible construction dust when possible',
    'Shorten vigorous outdoor sessions if symptoms appear',
  ],
}

const VAPID_PUBLIC_KEY ='BKQZlKonq6g7x2ocp8Z0z1Ay_CzkI832VCMDSMUbFgdkI9Px56qllIsB5qfZ1lajm7MmUJl6-30pv-ax4kI6f0o'

const selectedSuburb = ref('Melbourne')
const suburbs = ref([...FALLBACK_SUBURBS])
const areaBySuburb = ref({ Melbourne: { ...fallbackArea } })
const loading = ref(false)
const testingPush = ref(false)
const error = ref('')
const successMessage = ref('')
const locationEnabled = ref(true)
const pushEnabled = ref(false)

const currentLat = ref(null)
const currentLon = ref(null)
const usingPreciseLocation = ref(false)

const mapCenter = computed(() => {
  if (
    usingPreciseLocation.value &&
    typeof currentLat.value === 'number' &&
    typeof currentLon.value === 'number'
  ) {
    return {
      lat: currentLat.value,
      lon: currentLon.value,
      label: 'your current location',
    }
  }

  const suburbCoords = SUBURB_COORDS[selectedSuburb.value] || SUBURB_COORDS.Melbourne

  return {
    lat: suburbCoords.lat,
    lon: suburbCoords.lon,
    label: `${selectedSuburb.value} center`,
  }
})

const activeArea = computed(
  () => areaBySuburb.value[selectedSuburb.value] || fallbackArea
)

const getUserId = () => {
  let id = localStorage.getItem(USER_ID_KEY)
  if (!id) {
    id = crypto.randomUUID()
    localStorage.setItem(USER_ID_KEY, id)
  }
  return id
}

const API_BASE_URL = 'https://3z3kc4xlji.execute-api.ap-southeast-2.amazonaws.com'

const buildApiUrl = (path) => {
  return `${API_BASE_URL.replace(/\/$/, '')}${path}`
}

const buildPreferencesUrl = () => buildApiUrl('/user-preferences-api')
const buildSendDustAlertsUrl = () => buildApiUrl('/send-dust-alerts')
const buildCurrentRiskUrl = (suburbName) =>
  buildApiUrl(`/api/current-risk?suburb=${encodeURIComponent(suburbName)}`)


const normalizeSuburbName = (value = '') =>
  value
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/\b(vic|victoria|melbourne city|city of melbourne)\b/g, '')
    .replace(/[^a-z\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

const matchSupportedSuburb = (detectedSuburb = '') => {
  const normalizedDetected = normalizeSuburbName(detectedSuburb)
  if (!normalizedDetected) return 'Melbourne'

  const exactMatch = suburbs.value.find(
    (suburb) => normalizeSuburbName(suburb) === normalizedDetected
  )
  if (exactMatch) return exactMatch

  const partialMatch = suburbs.value.find((suburb) => {
    const normalizedSuburb = normalizeSuburbName(suburb)
    return (
      normalizedDetected.includes(normalizedSuburb) ||
      normalizedSuburb.includes(normalizedDetected)
    )
  })
  return partialMatch || 'Melbourne'
}

const getSuburbFromCoordinates = async (lat, lon) => {
  const response = await fetch(
    `https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&zoom=16&addressdetails=1`,
    {
      headers: {
        Accept: 'application/json',
      },
    }
  )

  if (!response.ok) {
    throw new Error(`Reverse geocoding failed (${response.status})`)
  }

  const data = await response.json()
  const address = data?.address || {}

  return (
    address.suburb ||
    address.neighbourhood ||
    address.city_district ||
    address.town ||
    address.city ||
    address.municipality ||
    'Melbourne'
  )
}

const loadCurrentRiskBySuburb = async (suburbName = 'Melbourne') => {
  try {
    const res = await fetch(buildCurrentRiskUrl(suburbName))
    const data = await res.json()
    if (!res.ok || !data.success) {
      throw new Error(data.error || `Current risk request failed (${res.status})`)
    }
    return {
      level: data?.overall_risk?.level || null,
      recommendation: data?.overall_risk?.recommendation || '',
    }
  } catch (err) {
    console.error('Failed to load current risk', err)
    return null
  }
}

const toBlocksText = (distanceM, sourceLabel) => {
  if (!Number.isFinite(distanceM)) {
    return `Distance from ${sourceLabel} unavailable`
  }

  const blocks = Math.max(1, Math.round(distanceM / 100))
  const roundedMeters = Math.round(distanceM)

  return `${blocks} ${blocks === 1 ? 'block' : 'blocks'} from ${sourceLabel} (${roundedMeters} m)`
}

const getSiteRiskMeta = (distanceM) => {
  if (Number.isFinite(distanceM) && distanceM <= 250) {
    return { riskLabel: 'High Risk', riskTone: 'high' }
  }
  if (Number.isFinite(distanceM) && distanceM <= 500) {
    return { riskLabel: 'Moderate Risk', riskTone: 'moderate' }
  }
  return { riskLabel: 'Low Risk', riskTone: 'low' }
}

const getSiteType = (site) =>
  site.workType ||
  site.permitType ||
  site.category ||
  site.description ||
  'Active construction work'

const mapNearbyPayloadToArea = (payload, suburbName = 'Melbourne', currentRisk = null) => {
  const queryMode = payload?.queryMode || 'suburb'
  const sourceLabel =
    queryMode === 'coords'
      ? 'your current location'
      : `${suburbName || payload?.selectedSuburb || 'selected suburb'} center`

  const activeSites = (payload?.sites || []).map((site) => {
    const distanceM = Number(site.distanceM)
    const riskMeta = getSiteRiskMeta(distanceM)

    return {
  siteId: site.siteId || `${site.address}-${site.distanceM}`,
  title: site.address || 'Unknown address',
  type: getSiteType(site),
  distance: toBlocksText(distanceM, sourceLabel),
  distanceM,
  lat: typeof site.lat === 'number' ? site.lat : null,
  lon: typeof site.lon === 'number' ? site.lon : null,
  ...riskMeta,
}
  })

  const locationLabel = suburbName || payload?.selectedSuburb || 'this area'
  const inCoverage = payload?.inCoverage !== false
  const hasSites = activeSites.length > 0
  const resultCount = Number(payload?.count ?? activeSites.length)
  const cappedAtFive = resultCount >= 5

  let summaryTitle = hasSites
    ? cappedAtFive
      ? 'At least 5 active construction sites nearby'
      : `${activeSites.length} active construction sites nearby`
    : 'No active construction sites nearby'
  let summaryText = hasSites
    ? queryMode === 'coords'
      ? 'Nearest active permits around your current location are shown below.'
      : `Nearest active permits around ${locationLabel} center are shown below.`
    : `No active permits were found near ${locationLabel} within your search radius.`

  if (!inCoverage) {
    summaryTitle = 'Outside City of Melbourne coverage'
    summaryText =
      payload?.message ||
      'You are currently outside the City of Melbourne coverage area.'
  }

  const showRisk = inCoverage

  return {
    lastUpdated: new Date().toLocaleTimeString('en-AU', {
      hour: 'numeric',
      minute: '2-digit',
    }),
    summaryEyebrow: 'NEARBY CONSTRUCTION SITES',
    summaryTitle,
    summaryText,
    riskLevel: showRisk ? currentRisk?.level || null : null,
    riskRecommendation: showRisk ? currentRisk?.recommendation || '' : '',
    activeSites,
    tips: fallbackArea.tips,
  }
}

const loadNearbyByCoords = async (lat, lon, suburbName = 'Melbourne') => {
  loading.value = true
  error.value = ''

  try {
    const nearbyRes = await fetch(
      buildApiUrl(
        `/v1/construction/nearby?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&radius=800`
      )
    )
    const data = await nearbyRes.json()

    if (!nearbyRes.ok || !data.ok) {
      throw new Error(data.message || `Nearby sites request failed (${nearbyRes.status})`)
    }

    let currentRisk = null
    if (data.inCoverage !== false) {
      currentRisk = await loadCurrentRiskBySuburb(suburbName)
    }

    areaBySuburb.value = {
      ...areaBySuburb.value,
      [suburbName]: mapNearbyPayloadToArea(data, suburbName, currentRisk),
    }
  } catch (err) {
    error.value = err.message || 'Could not load dust risk data right now.'
  } finally {
    loading.value = false
  }
}

const loadNearbyBySuburb = async (suburbName = 'Melbourne') => {
  loading.value = true
  error.value = ''

  try {
    const [nearbyRes, currentRisk] = await Promise.all([
      fetch(
        buildApiUrl(
          `/v1/construction/nearby?suburb=${encodeURIComponent(suburbName)}&radius=800`
        )
      ),
      loadCurrentRiskBySuburb(suburbName),
    ])
    const data = await nearbyRes.json()

    if (!nearbyRes.ok || !data.ok) {
      throw new Error(data.message || `Nearby sites request failed (${nearbyRes.status})`)
    }

    areaBySuburb.value = {
      ...areaBySuburb.value,
      [suburbName]: mapNearbyPayloadToArea(data, suburbName, currentRisk),
    }
  } catch (err) {
    error.value = err.message || 'Could not load nearby construction sites right now.'
  } finally {
    loading.value = false
  }
}

const savePreferences = async (pushSubscription = undefined) => {
  try {
    const body = {
      locationEnabled: locationEnabled.value,
      selectedSuburb: selectedSuburb.value,
      pushEnabled: pushEnabled.value,
    }

    if (pushSubscription !== undefined) {
      body.pushSubscription = pushSubscription
    }

    await fetch(buildPreferencesUrl(), {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'X-Anonymous-User-Id': getUserId(),
      },
      body: JSON.stringify(body),
    })
  } catch (err) {
    console.error('Failed to save preferences', err)
  }
}

const loadPreferences = async () => {
  try {
    const res = await fetch(buildPreferencesUrl(), {
      headers: {
        'X-Anonymous-User-Id': getUserId(),
      },
    })

    const data = await res.json()

    if (data.ok && data.preferences) {
      locationEnabled.value =
        typeof data.preferences.locationEnabled === 'boolean'
          ? data.preferences.locationEnabled
          : true

      selectedSuburb.value =
        typeof data.preferences.selectedSuburb === 'string' &&
        data.preferences.selectedSuburb.trim()
          ? data.preferences.selectedSuburb.trim()
          : 'Melbourne'

      pushEnabled.value =
        typeof data.preferences.pushEnabled === 'boolean'
          ? data.preferences.pushEnabled
          : false
    }
  } catch (err) {
    console.error('Failed to load preferences', err)
  }
}

const selectSuburb = async (suburb) => {
  usingPreciseLocation.value = false
  currentLat.value = null
  currentLon.value = null
  selectedSuburb.value = suburb
  await savePreferences()

  if (areaBySuburb.value[suburb]) return

  await loadNearbyBySuburb(suburb)
}

const saveLocationPreference = async () => {
  await savePreferences()
}

const handlePushToggle = async () => {
  try {
    error.value = ''
    successMessage.value = ''

    if (pushEnabled.value) {
      await requestNotificationPermission()

      if (!VAPID_PUBLIC_KEY || VAPID_PUBLIC_KEY === 'YOUR_PUBLIC_VAPID_KEY_HERE') {
        throw new Error('Missing public VAPID key')
      }

      const subscription = await subscribeToPush(VAPID_PUBLIC_KEY)
      await savePreferences(subscription.toJSON())
      successMessage.value = 'Dust alerts enabled successfully.'
    } else {
      await unsubscribeFromPush()
      await savePreferences(null)
      successMessage.value = 'Dust alerts disabled.'
    }
  } catch (err) {
    console.error('Push toggle failed', err)
    pushEnabled.value = false
    error.value = err.message || 'Could not enable push notifications.'
  }
}

const sendTestPush = async () => {
  try {
    testingPush.value = true
    error.value = ''
    successMessage.value = ''

    const res = await fetch(buildSendDustAlertsUrl(), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        userId: getUserId(),
      }),
    })

    const data = await res.json()

    if (!res.ok || !data.ok) {
      throw new Error(data.message || `Test push failed (${res.status})`)
    }

    successMessage.value = 'Test notification sent. Check your browser notifications.'
  } catch (err) {
    console.error('Test push failed', err)
    error.value = err.message || 'Could not send test notification.'
  } finally {
    testingPush.value = false
  }
}

const useMyLocation = async () => {
  if (!locationEnabled.value || !navigator.geolocation) return

  loading.value = true
  error.value = ''
  successMessage.value = ''

  navigator.geolocation.getCurrentPosition(
    async (position) => {
      try {
        const { latitude, longitude } = position.coords
        currentLat.value = latitude
        currentLon.value = longitude
        usingPreciseLocation.value = true
        const detectedSuburb = await getSuburbFromCoordinates(latitude, longitude)
        const matchedSuburb = matchSupportedSuburb(detectedSuburb)

        selectedSuburb.value = matchedSuburb
        await loadNearbyByCoords(latitude, longitude, matchedSuburb)
        await savePreferences()

        successMessage.value = `Using your location. Suburb set to ${matchedSuburb}.`
      } catch (err) {
        console.error('Failed to resolve suburb from coordinates', err)
        await loadNearbyByCoords(
          position.coords.latitude,
          position.coords.longitude,
          selectedSuburb.value
        )
        await savePreferences()
        error.value =
          'We found your location, but could not match it to a supported suburb automatically.'
      }
    },
    () => {
      loading.value = false
      error.value = 'Location access failed. Showing suburb-based estimates instead.'
    },
    { enableHighAccuracy: true, timeout: 12000 }
  )
}

onMounted(async () => {
  await loadPreferences()
  await selectSuburb(selectedSuburb.value)
})
</script>

<style scoped>
.construction-page {
  background: var(--bg-page);
  min-height: 100vh;
}

.dust-hero {
  background: linear-gradient(135deg, #f0627e, #d87a46);
  padding: 56px 0 76px;
}

.hero-top {
  margin-bottom: 48px;
}

.hero-brand {
  display: flex;
  align-items: center;
  gap: 10px;
  color: white;
}

.hero-brand-icon {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  background: rgba(255, 255, 255, 0.92);
  color: #eb5a73;
  display: grid;
  place-items: center;
  font-size: 16px;
}

.hero-brand-name {
  font-size: 18px;
  font-weight: 500;
}

.hero-back-link {
  color: rgba(255, 255, 255, 0.94);
  font-size: 18px;
}

.hero-copy h1 {
  margin: 0 0 20px;
  max-width: 560px;
  font-size: 72px;
  line-height: 1.02;
  font-weight: 400;
  color: white;
}

.hero-copy p {
  margin: 0;
  max-width: 640px;
  font-size: 22px;
  line-height: 1.5;
  color: rgba(255, 255, 255, 0.94);
}

.dust-content {
  padding-top: 42px;
}

.suburb-card {
  padding: 42px 44px;
  margin-bottom: 46px;
}

.suburb-card h2 {
  margin: 0 0 14px;
  font-size: 34px;
  font-weight: 500;
  color: var(--text-dark);
}

.suburb-card p {
  margin: 0 0 28px;
  color: var(--text-muted);
  font-size: 18px;
  line-height: 1.6;
}

.privacy-controls,
.push-controls {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 20px;
}

.privacy-toggle {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  font-size: 15px;
  color: #4d5969;
  font-weight: 600;
}

.push-help {
  margin: 0 0 24px;
  font-size: 14px;
  color: #6a7585;
}

.suburb-grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 16px;
  margin-bottom: 30px;
}

.suburb-pill {
  border: 1px solid #d9dee7;
  background: #f8f9fb;
  color: #394354;
  border-radius: 18px;
  padding: 18px 16px;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
  transition: 0.2s ease;
}

.suburb-pill:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.suburb-pill.active {
  background: linear-gradient(135deg, #ff6f88, #ff5b76);
  border-color: transparent;
  color: white;
  box-shadow: 0 10px 20px rgba(255, 82, 115, 0.2);
}

.test-btn {
  white-space: nowrap;
}

.updated-row {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #778090;
  font-size: 15px;
  font-weight: 600;
}

.updated-dot {
  font-size: 16px;
}

.risk-highlight {
  margin-top: 18px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.risk-label {
  font-size: 13px;
  font-weight: 700;
  color: #6b7280;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.risk-badge {
  display: inline-block;
  width: fit-content;
  border-radius: 999px;
  padding: 10px 18px;
  font-size: 15px;
  font-weight: 800;
}

.risk-badge.high {
  color: #ea2951;
  background: #fad9df;
  border: 1px solid #f3c0ca;
}

.risk-badge.moderate {
  color: #d36c00;
  background: #f9ebbe;
  border: 1px solid #f0d35e;
}

.risk-badge.low {
  color: #11915d;
  background: #ccf0e0;
  border: 1px solid #9be0bf;
}

.risk-recommendation {
  margin: 0;
  font-size: 15px;
  color: #33465f;
  line-height: 1.6;
}

.risk-summary-card {
  position: relative;
  min-height: 300px;
  border-radius: 30px;
  overflow: hidden;
  box-shadow: var(--shadow-soft);
  margin-bottom: 52px;
  border: 1px solid #f3d8dc;
}

.risk-summary-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.risk-summary-overlay {
  position: absolute;
  inset: 0;
  background: rgba(255, 243, 245, 0.92);
}

.risk-summary-content {
  position: relative;
  z-index: 2;
  display: flex;
  gap: 26px;
  align-items: flex-start;
  padding: 44px 46px;
  max-width: 980px;
}

.risk-summary-icon {
  width: 96px;
  height: 96px;
  min-width: 96px;
  border-radius: 50%;
  background: #f8cdd4;
  display: grid;
  place-items: center;
  font-size: 42px;
}

.risk-summary-tag {
  margin: 6px 0 14px;
  color: #ef2f55;
  font-size: 14px;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.risk-summary-content h2 {
  margin: 0 0 14px;
  font-size: 36px;
  font-weight: 500;
  line-height: 1.15;
}

.risk-summary-text {
  margin: 0 0 18px;
  max-width: 760px;
  color: #475467;
  font-size: 18px;
  line-height: 1.7;
}

.risk-level-text {
  margin: 0 0 16px;
  max-width: 820px;
  color: #33465f;
  font-size: 16px;
  line-height: 1.6;
}

.sites-section {
  margin-bottom: 52px;
}

.sites-heading {
  margin: 0 0 24px;
  font-size: 34px;
  font-weight: 500;
  color: var(--text-dark);
}

.sites-list {
  display: grid;
  gap: 28px;
}

.site-card {
  display: flex;
  justify-content: space-between;
  gap: 20px;
  align-items: flex-start;
  padding: 34px 36px;
  border-radius: 28px;
  border: 1px solid transparent;
  box-shadow: var(--shadow-soft);
}

.site-card.high {
  background: #fbefef;
  border-color: #f3d2d7;
}

.site-card.moderate {
  background: #f8f4e6;
  border-color: #efd990;
}

.site-card.low {
  background: #e8f8f2;
  border-color: #bae8d7;
}

.site-card-main h3 {
  margin: 0 0 10px;
  font-size: 28px;
  font-weight: 500;
  line-height: 1.25;
  color: var(--text-dark);
}

.site-card-type {
  margin: 0 0 18px;
  font-size: 16px;
  color: #5d6777;
}

.site-card-distance {
  margin: 0;
  font-size: 14px;
  font-weight: 700;
  color: #354255;
}

.site-risk-badge {
  border-radius: 999px;
  padding: 14px 20px;
  font-size: 15px;
  font-weight: 800;
  white-space: nowrap;
}

.site-risk-badge.high {
  color: #ea2951;
  background: #fad9df;
  border: 1px solid #f3c0ca;
}

.site-risk-badge.moderate {
  color: #d36c00;
  background: #f9ebbe;
  border: 1px solid #f0d35e;
}

.site-risk-badge.low {
  color: #11915d;
  background: #ccf0e0;
  border: 1px solid #9be0bf;
}

.dust-actions-panel {
  position: relative;
  min-height: 360px;
  border-radius: 30px;
  overflow: hidden;
  box-shadow: var(--shadow-soft);
}

.dust-actions-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.dust-actions-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    90deg,
    rgba(8, 150, 123, 0.9),
    rgba(8, 150, 123, 0.78)
  );
}

.dust-actions-content {
  position: relative;
  z-index: 2;
  padding: 50px 56px;
  color: white;
  max-width: 820px;
}

.dust-actions-content h2 {
  margin: 0 0 26px;
  font-size: 34px;
  font-weight: 500;
}

.dust-actions-list {
  margin: 0 0 34px;
  padding-left: 22px;
}

.dust-actions-list li {
  margin-bottom: 20px;
  font-size: 18px;
  line-height: 1.6;
}

.dust-actions-btn {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  background: white;
  color: #0f7f67;
  border-radius: 999px;
  padding: 18px 30px;
  font-size: 18px;
  font-weight: 700;
  text-decoration: none;
}

.error-text {
  margin-top: 20px;
  color: #c0392b;
  font-weight: 600;
}

.success-text {
  margin-top: 20px;
  color: #0f7f67;
  font-weight: 600;
}

@media (max-width: 1100px) {
  .suburb-grid {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}

@media (max-width: 992px) {
  .hero-copy h1 {
    font-size: 54px;
  }

  .suburb-card {
    padding: 30px 26px;
  }

  .risk-summary-content {
    padding: 34px 28px;
  }

  .dust-actions-content {
    padding: 36px 30px;
  }
}

@media (max-width: 768px) {
  .dust-hero {
    padding: 40px 0 56px;
  }

  .hero-brand {
    flex-wrap: wrap;
  }

  .hero-copy h1 {
    font-size: 42px;
    max-width: 100%;
  }

  .hero-copy p {
    font-size: 18px;
  }

  .suburb-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .privacy-controls,
  .push-controls {
    flex-direction: column;
    align-items: flex-start;
  }

  .risk-summary-content {
    flex-direction: column;
  }

  .risk-summary-icon {
    width: 82px;
    height: 82px;
    min-width: 82px;
    font-size: 36px;
  }

  .risk-summary-content h2,
  .suburb-card h2 {
    font-size: 28px;
  }

  .dust-actions-content h2 {
    font-size: 28px;
  }

  .dust-actions-list li,
  .suburb-card p {
    font-size: 16px;
  }

  .site-card {
    flex-direction: column;
    padding: 26px 22px;
  }

  .site-card-main h3,
  .sites-heading {
    font-size: 26px;
  }

  .site-risk-badge {
    align-self: flex-start;
  }

  

  .dust-actions-btn {
    font-size: 16px;
    padding: 16px 24px;
  }
}
</style>
